# For mantles
- type: loadoutEffectGroup
  id: MasterHoS
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 72000 #20 hrs

# For the veteran head of security cosmetics
- type: loadoutEffectGroup
  id: VeteranHOS
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 180000 #50 hrs

# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS

- type: loadout
  id: HeadofSecurityJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS

- type: loadout
  id: HeadofSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt

- type: loadout
  id: HeadofSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt

- type: loadout
  id: HeadofSecurityFormalSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHosFormal

- type: loadout
  id: HeadofSecurityFormalSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHosFormal

# Head
- type: loadout
  id: HeadofSecurityHead
  equipment:
    head: ClothingHeadHatHoshat

- type: loadout
  id: HeadofSecurityBeret
  equipment:
    head: ClothingHeadHatBeretHoS

# Neck
- type: loadout
  id: HeadofSecurityCloak
  equipment:
    neck: ClothingNeckCloakHos

- type: loadout
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: startingGear
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS

# OuterClothing
- type: loadout
  id: HeadofSecurityCoat
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench

- type: loadout
  id: HeadofSecurityWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterHoS

- type: loadout
  id: HeadofSecurityWinterCoatUnarmored
  equipment:
    outerClothing: ClothingOuterWinterHoSUnarmored

# Headset
- type: loadout
  id: HeadofSecurityHeadsetBasic
  equipment:
    ears: ClothingHeadsetHOS

- type: loadout
  id: HeadofSecurityHeadset
  equipment:
    ears: ClothingHeadsetAltSecurity

- type: loadout
  id: HeadofSecurityVeteranHeadset
  equipment:
    ears: ClothingHeadsetHOSveteran
  effects:
  - !type:GroupLoadoutEffect
    proto: VeteranHOS

# A mask so the HoS can choose to spawn with the standard security gas mask that their new survival box removes
- type: loadout
  id: HeadofSecurityMask
  equipment:
    mask: ClothingMaskGasSecurity
